version: '3'
services:
  dbpostgres:
    image: postgres:10
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  app:
    build:
      context: .
    depends_on:
      - 'dbpostgres'
    ports:
      - '3000:3000'
    links:
      - 'dbpostgres'
