version: '3'
services:
  dbpostgres:
    image: postgres:10
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
