apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: asia.gcr.io/gke-101-276011/gke-node:v2
          ports:
            - containerPort: 3000
          env:
            - name: PROJECT_ENV
              valueFrom:
                secretKeyRef:
                  name: gke101-secret
                  key: project_env
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: gke101-secret
                  key: port

---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  type: NodePort
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
