apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-web-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke101-web-static-ip
    networking.gke.io/managed-certificates: be-ngong-cer
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: node-api-service
              servicePort: 3000
