apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-web-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: gke101-web-static-ip
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          serviceName: node-api-service
          servicePort: 3000
